name: Intuical
favicon: null
layout_spectrum: 0.594914223998785
typography_spectrum: 0.9667630163021386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.608692966401577
  lightness: 0.8318508365191519
  saturation: 0.530858151614666
  rhythmicContrast: 0.5137738198973238
purpose: []
